# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm install -f
    - run: npm run build --prod --base-href https://nipunrautela.me/febwishes
    # - name: Deploy to GitHub Pages
    #   run: |
    #     git config --global user.email "you@example.com"
    #     git config --global user.name "Nipun Rautela"
    #     npx angular-cli-ghpages --dir=dist/febwishes/browser --no-silent
    #     # npm install -g @angular/cli
    #     # ng add angular-cli-ghpages --skip-confirmation --force
    #     # ng deploy --base-href=/febwishes
    #   env:
    #     CI: true
    #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Build Jekyll for GitHub Pages
      uses: actions/jekyll-build-pages@v1.0.13
      with:
        # Directory where the source files reside.
        source: dist/febwishes/browser # optional, default is ./
        # Output directory of the build. Although it can be nested inside the source, it cannot be the same as the source directory.
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v4.0.0
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4.0.5
              
